Fix 'ontick' not working
Batfoxkid/Freak-Fortress-2-Rewrite pull request #155
Opened 2023-12-29 17:08 UTC by naydef

2023-12-29 23:05 UTC, Batfoxkid requested changes

2023-12-29 23:05 UTC, Batfoxkid commented on addons/sourcemod/scripting/ff2r_menu_abilities.sp
> +					SetBossCharge(boss, key, amount);
Would be better if the charge was set within the statement that changed the amount so we avoid setting the same amount.

2023-12-29 23:43 UTC, naydef commented on addons/sourcemod/scripting/ff2r_menu_abilities.sp
> +					SetBossCharge(boss, key, amount);
Done

2023-12-30 00:05 UTC, Batfoxkid approved these changes

2023-12-30 00:05 UTC, merged