Eureka Fix
Batfoxkid/Freak-Fortress-2-Rewrite pull request #24
Opened 2022-07-29 21:28 UTC by minesettimi

A number was incorrect on the eureka fix that allowed for the engineer to still teleport to home with the command.

2022-07-29 22:22 UTC, minesettimi commented
fixed number mixup now fully tested and working

2022-07-29 22:58 UTC, Batfoxkid requested changes

2022-07-29 22:58 UTC, Batfoxkid commented on addons/sourcemod/scripting/freak_fortress_2/commands.sp
>  					if(StringToInt(buffer) == 1)
You can remove this check here since it's already checked for in the added lines.

2022-07-30 04:03 UTC, minesettimi commented
was fixed in the 2nd commit

2022-07-30 04:18 UTC, Batfoxkid commented
> was fixed in the 2nd commit

[`if(StringToInt(buffer) == 1)`](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/pull/24/files#diff-b43c26b85602304d4197539cedc39d08fe0967515bffa2fff3f81bbd245d7ad6R309) still exists even with [`if (StringToInt(buffer) == 0)`](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/pull/24/files#diff-b43c26b85602304d4197539cedc39d08fe0967515bffa2fff3f81bbd245d7ad6R319) being used before.

2022-07-30 04:21 UTC, minesettimi commented
should be good now

2022-07-30 20:45 UTC, Batfoxkid commented on addons/sourcemod/scripting/freak_fortress_2/commands.sp
> +					if(teletype == 1)
This check still isn't needed at you already checked if the teletype isn't zero in the above change.

2022-08-02 03:18 UTC, minesettimi commented
adjusted the code to only check the type of teleport once

2022-08-02 03:52 UTC, Batfoxkid approved these changes

2022-08-02 03:53 UTC, merged