Add player glow to last player on team (configurable)
Batfoxkid/Freak-Fortress-2-Rewrite pull request #25
Opened 2022-08-03 19:43 UTC by minesettimi

If the convar is enabled the last player on a team (bosses excluded) is highlighted to make it easier to move the end of the round along especially if the last player is hiding from the boss.

2022-08-03 21:25 UTC, Batfoxkid requested changes
Is it on purpose that bosses aren't affected by the outline?

2022-08-03 21:25 UTC, Batfoxkid commented on addons/sourcemod/scripting/freak_fortress_2/gamemode.sp
> +			if(PlayersAlive[team] < 2) {
Change this to match the rest of the code format with

```c
if(statement)
{
```

2022-08-03 22:38 UTC, minesettimi commented
Sort of, I felt it wasn't as necessary for the boss but also I cant seem to find a way to implement it.

2022-08-04 02:42 UTC, Batfoxkid approved these changes
> Sort of, I felt it wasn't as necessary for the boss but also I cant seem to find a way to implement it.

This could possibly be added in the future, I'll take this as it is now.

2022-08-04 02:43 UTC, merged